#!/bin/sh

# Modify it to your configuration
DIR=/mnt/app/redmine/
PATH=$PATH:/usr/local/ruby/bin
# Start Redmine in daemon mode.
start(){
    cd $DIR
    bundle exec unicorn_rails -c config/unicorn.rb -E production -D
}

# Stop Redmine daemon
stop(){
    cd $DIR
    kill -2 `cat pids/unicorn.pid`
}



case "$1" in
	start)
		start
		;;
	
	stop)
		stop
		;;
	
	restart|force-reload)
		stop
		start
		;;

	*)
		echo "Usage: $0 {start|stop|restart|force-reload|status}"
		exit 1

esac

